In [165]:
#importing common libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Extracting information from the wikipedia URL
#Tried multiple methods, found this to work best.. it also use bs4 refernce of beautiful soup

In [166]:
data = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M', flavor='bs4', header=0)
df = data[0]

In [167]:
df.head()

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

In [168]:
#Ignoring Borough = Not assigned
df.drop(df[df['Borough'] == 'Not assigned'].index, inplace=True)

In [169]:
df.head(15)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern
14      M3B        North York   Don Mills North
15      M4B         East York  Woodbine Gardens
16      M4B         East York     Parkview Hill
17      M5B  Downtown Toronto           Ryerson
18      M5B  Downtown Toronto   Garden District

In [146]:
df['Neighbourhood'] = df.groupby(['Postcode','Borough'])['Neighbourhood']\
       .apply(lambda x: x.cumsum())
df.head()

  Postcode           Borough            Neighbourhood
2      M3A        North York                Parkwoods
3      M4A        North York         Victoria Village
4      M5A  Downtown Toronto             Harbourfront
5      M5A  Downtown Toronto  HarbourfrontRegent Park
6      M6A        North York         Lawrence Heights

In [170]:
#Dropping duplicate values
df.drop_duplicates(subset=['Postcode','Borough'], keep='last', inplace=True)

In [171]:
df.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
5       M5A  Downtown Toronto       Regent Park
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
12      M1B       Scarborough           Malvern
14      M3B        North York   Don Mills North
16      M4B         East York     Parkview Hill
18      M5B  Downtown Toronto   Garden District

In [172]:
df.shape

(103, 3)

Add latitude and longitude

In [173]:
df1= pd.read_csv('https://ibm.box.com/shared/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv')

In [174]:
df1.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [178]:
df = df.merge(df1, how='left', left_on='Postcode', right_on='Postal Code')

In [179]:
df.head()

,Postcode,Borough,Neighbourhood,Postal Code,Latitude,Longitude
0,M3A,North York,Parkwoods,M3A,43.753259,-79.329656
1,M4A,North York,Victoria Village,M4A,43.725882,-79.315572
2,M5A,Downtown Toronto,Regent Park,M5A,43.654260,-79.360636
3,M6A,North York,Lawrence Manor,M6A,43.718518,-79.464763
4,M7A,Queen's Park,Not assigned,M7A,43.662301,-79.389494

Cluster Neighborhoods

Run *k*-means to cluster the neighborhood into 5 clusters.